services:
  webserver:
    build:
      context: ./frankenphp
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      PHP_IDE_CONFIG: 'serverName=localhost'
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true

  database:
    ports:
      - ${DATABASE_PORT:-5432}:5432

  node:
    build:
      context: ./node
    volumes:
      - ./:/app
    ports:
      - 5173:5173